
version: '3.4'

services:
  jsmpeg:
    image: jsmpeg_ov
    ports:
      - "7879:7879"
      - "7880:7880"
      - "7881:7881"
      - "7882:7882"
    container_name: jsmpeg_ov
    hostname: jsmpeg_ov
